// Angular/src/app/features/forms/field-editor/field-editor.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { FormField } from '../../../models/form.model';

@Component({
  selector: 'app-field-editor',
  templateUrl: './field-editor.component.html',
  styleUrls: ['./field-editor.component.scss']
})
export class FieldEditorComponent {
  @Input() set selectedField(field: FormField | null) {
    this._selectedField = field;
    this.initForm();
  }
  get selectedField(): FormField | null {
    return this._selectedField;
  }
  
  @Input() readOnly = false;
  
  @Output() updateField = new EventEmitter<{id: string, updates: Partial<FormField>}>();
  
  private _selectedField: FormField | null = null;
  fieldForm: FormGroup;
  
  constructor(private fb: FormBuilder) {
    this.fieldForm = this.fb.group({
      label: ['', Validators.required],
      placeholder: [''],
      required: [false],
      validation: this.fb.group({
        message: ['']
      }),
      scoring: this.fb.group({
        enabled: [false],
        maxPoints: [10],
        weightMultiplier: [1],
        requiresManualReview: [false]
      })
    });
  }
  
  initForm(): void {
    if (!this.selectedField) {
      this.fieldForm.reset();
      return;
    }
    
    this.fieldForm.patchValue({
      label: this.selectedField.label,
      placeholder: this.selectedField.placeholder || '',
      required: this.selectedField.required,
      validation: {
        message: this.selectedField.validation?.message || ''
      },
      scoring: {
        enabled: this.selectedField.scoring?.enabled || false,
        maxPoints: this.selectedField.scoring?.maxPoints || 10,
        weightMultiplier: this.selectedField.scoring?.weightMultiplier || 1,
        requiresManualReview: this.selectedField.scoring?.requiresManualReview || false
      }
    });
    
    // Disable form if in read-only mode
    if (this.readOnly) {
      this.fieldForm.disable();
    } else {
      this.fieldForm.enable();
    }
    
    // Listen for form changes
    this.fieldForm.valueChanges.subscribe(value => {
      if (this.selectedField && !this.readOnly) {
        this.updateField.emit({
          id: this.selectedField.id,
          updates: value
        });
      }
    });
  }
  
  addOption(): void {
    if (this.readOnly || !this.selectedField) return;
    
    const currentOptions = this.selectedField.options || [];
    this.updateField.emit({
      id: this.selectedField.id,
      updates: { options: [...currentOptions, `Option ${currentOptions.length + 1}`] }
    });
  }
  
  updateOption(index: number, value: string): void {
    if (this.readOnly || !this.selectedField || !this.selectedField.options) return;
    
    const newOptions = [...this.selectedField.options];
    newOptions[index] = value;
    
    this.updateField.emit({
      id: this.selectedField.id,
      updates: { options: newOptions }
    });
  }
  
  removeOption(index: number): void {
    if (this.readOnly || !this.selectedField || !this.selectedField.options) return;
    
    const newOptions = this.selectedField.options.filter((_, idx) => idx !== index);
    
    this.updateField.emit({
      id: this.selectedField.id,
      updates: { options: newOptions }
    });
  }
  
  addCorrectAnswer(): void {
    if (this.readOnly || !this.selectedField) return;
    
    const currentAnswers = this.selectedField.scoring?.correctAnswers || [];
    
    this.updateField.emit({
      id: this.selectedField.id,
      updates: { 
        scoring: {
          ...this.selectedField.scoring,
          enabled: this.selectedField.scoring?.enabled || false,
          correctAnswers: [...currentAnswers, '']
        }
      }
    });
  }
  
  updateCorrectAnswer(index: number, value: string): void {
    if (this.readOnly || !this.selectedField || !this.selectedField.scoring?.correctAnswers) return;
    
    const newAnswers = [...this.selectedField.scoring.correctAnswers];
    newAnswers[index] = value;
    
    this.updateField.emit({
      id: this.selectedField.id,
      updates: { 
        scoring: {
          ...this.selectedField.scoring,
          correctAnswers: newAnswers
        }
      }
    });
  }
  
  removeCorrectAnswer(index: number): void {
    if (this.readOnly || !this.selectedField || !this.selectedField.scoring?.correctAnswers) return;
    
    const newAnswers = this.selectedField.scoring.correctAnswers.filter((_, idx) => idx !== index);
    
    this.updateField.emit({
      id: this.selectedField.id,
      updates: { 
        scoring: {
          ...this.selectedField.scoring,
          correctAnswers: newAnswers
        }
      }
    });
  }
}
<mat-card class="field-editor-card">
  <mat-card-header>
    <mat-card-title class="field-editor-title">
      <mat-icon *ngIf="readOnly">lock</mat-icon>
      Field Properties
      <span *ngIf="readOnly" class="read-only-label">(Read Only)</span>
    </mat-card-title>
  </mat-card-header>
  
  <mat-card-content class="field-editor-content">
    <!-- No Field Selected State -->
    <div *ngIf="!selectedField" class="no-field-selected">
      <p>
        {{ readOnly ? "Published form - Select a field to view properties" : "Select a field to edit its properties" }}
      </p>
    </div>
    
    <!-- Field Properties Form -->
    <form *ngIf="selectedField" [formGroup]="fieldForm" class="field-form">
      <!-- Basic Properties -->
      <mat-form-field appearance="outline">
        <mat-label>Label</mat-label>
        <input matInput formControlName="label">
      </mat-form-field>
      
      <mat-form-field appearance="outline">
        <mat-label>Placeholder</mat-label>
        <input matInput formControlName="placeholder">
      </mat-form-field>
      
      <div class="field-checkbox">
        <mat-checkbox formControlName="required">Required field</mat-checkbox>
      </div>
      
      <!-- Options for Select, Radio, Checkbox -->
      <div *ngIf="['select', 'radio', 'checkbox'].includes(selectedField.type)" class="field-options">
        <h3>Options</h3>
        
        <div *ngFor="let option of selectedField.options; let i = index" class="option-row">
          <mat-form-field appearance="outline" class="option-input">
            <input matInput [value]="option" (input)="updateOption(i, $any($event.target).value)">
          </mat-form-field>
          
          <button mat-icon-button color="warn" (click)="removeOption(i)" [disabled]="readOnly">
            <mat-icon>close</mat-icon>
          </button>
        </div>
        
        <button mat-stroked-button (click)="addOption()" [disabled]="readOnly" class="add-option-button">
          <mat-icon>add</mat-icon>
          Add Option
        </button>
      </div>
      
      <!-- Scoring Configuration -->
      <div class="scoring-section" formGroupName="scoring">
        <div class="scoring-header">
          <h3>Scoring</h3>
          <mat-slide-toggle formControlName="enabled">Enable scoring</mat-slide-toggle>
        </div>
        
        <div *ngIf="fieldForm.get('scoring.enabled')?.value" class="scoring-options">
          <mat-form-field appearance="outline">
            <mat-label>Maximum Points</mat-label>
            <input matInput type="number" formControlName="maxPoints">
          </mat-form-field>
          
          <mat-form-field appearance="outline">
            <mat-label>Weight Multiplier</mat-label>
            <mat-select formControlName="weightMultiplier">
              <mat-option [value]="1">1x (Normal)</mat-option>
              <mat-option [value]="2">2x (Double)</mat-option>
              <mat-option [value]="3">3x (Triple)</mat-option>
              <mat-option [value]="4">4x (Quadruple)</mat-option>
              <mat-option [value]="5">5x (Quintuple)</mat-option>
            </mat-select>
          </mat-form-field>
          
          <!-- Correct Answers for Select, Radio, Checkbox -->
          <div *ngIf="['select', 'radio', 'checkbox'].includes(selectedField.type)" class="correct-answers">
            <h4>Correct Answers</h4>
            
            <div *ngFor="let answer of selectedField.scoring?.correctAnswers || []; let i = index" class="option-row">
              <mat-form-field appearance="outline" class="option-input">
                <mat-select [value]="answer" (selectionChange)="updateCorrectAnswer(i, $event.value)">
                  <mat-option *ngFor="let option of selectedField.options" [value]="option">
                    {{ option }}
                  </mat-option>
                </mat-select>
              </mat-form-field>
              
              <button mat-icon-button color="warn" (click)="removeCorrectAnswer(i)" [disabled]="readOnly">
                <mat-icon>close</mat-icon>
              </button>
            </div>
            
            <button mat-stroked-button (click)="addCorrectAnswer()" [disabled]="readOnly" class="add-option-button">
              <mat-icon>add</mat-icon>
              Add Correct Answer
            </button>
          </div>
          
          <div class="field-checkbox">
            <mat-checkbox formControlName="requiresManualReview">Requires manual review</mat-checkbox>
          </div>
        </div>
      </div>
      
      <!-- Validation Message -->
      <div formGroupName="validation">
        <mat-form-field appearance="outline">
          <mat-label>Validation Message</mat-label>
          <textarea matInput formControlName="message" rows="2" placeholder="Custom validation message"></textarea>
        </mat-form-field>
      </div>
    </form>
  </mat-card-content>
</mat-card>

// src/components/FieldEditor.tsx

import { FormField } from "@/types/form";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Plus, X, Lock } from "lucide-react";

interface FieldEditorProps {
  selectedField: FormField | null;
  onUpdateField: (fieldId: string, updates: Partial<FormField>) => void;
  readOnly?: boolean;
}

export const FieldEditor = ({ selectedField, onUpdateField, readOnly = false }: FieldEditorProps) => {
  if (!selectedField) {
    return (
      <Card className="h-full">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            {readOnly && <Lock className="h-4 w-4" />}
            Field Properties
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-gray-500 text-center py-8">
            {readOnly ? "Published form - Select a field to view properties" : "Select a field to edit its properties"}
          </p>
        </CardContent>
      </Card>
    );
  }

  const updateField = (updates: Partial<FormField>) => {
    if (!readOnly) {
      onUpdateField(selectedField.id, updates);
    }
  };

  const updateScoring = (updates: Partial<NonNullable<FormField['scoring']>>) => {
    if (!readOnly) {
      updateField({
        scoring: {
          ...selectedField.scoring,
          enabled: selectedField.scoring?.enabled || false,
          ...updates
        }
      });
    }
  };

  const addOption = () => {
    if (readOnly) return;
    const currentOptions = selectedField.options || [];
    updateField({ options: [...currentOptions, `Option ${currentOptions.length + 1}`] });
  };

  const updateOption = (index: number, value: string) => {
    if (readOnly) return;
    const newOptions = [...(selectedField.options || [])];
    newOptions[index] = value;
    updateField({ options: newOptions });
  };

  const removeOption = (index: number) => {
    if (readOnly) return;
    const newOptions = selectedField.options?.filter((_, idx) => idx !== index);
    updateField({ options: newOptions });
  };

  const addCorrectAnswer = () => {
    if (readOnly) return;
    const currentAnswers = selectedField.scoring?.correctAnswers || [];
    updateScoring({ correctAnswers: [...currentAnswers, ''] });
  };

  const updateCorrectAnswer = (index: number, value: string) => {
    if (readOnly) return;
    const newAnswers = [...(selectedField.scoring?.correctAnswers || [])];
    newAnswers[index] = value;
    updateScoring({ correctAnswers: newAnswers });
  };

  const removeCorrectAnswer = (index: number) => {
    if (readOnly) return;
    const newAnswers = selectedField.scoring?.correctAnswers?.filter((_, idx) => idx !== index);
    updateScoring({ correctAnswers: newAnswers });
  };

  return (
    <Card className="h-full overflow-auto">
      <CardHeader>
        <CardTitle className="text-lg flex items-center gap-2">
          {readOnly && <Lock className="h-4 w-4" />}
          Field Properties
          {readOnly && <span className="text-sm font-normal text-gray-500">(Read Only)</span>}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <Label htmlFor="field-label">Label</Label>
          <Input
            id="field-label"
            value={selectedField.label}
            onChange={(e) => updateField({ label: e.target.value })}
            className="mt-1"
            readOnly={readOnly}
            disabled={readOnly}
          />
        </div>

        <div>
          <Label htmlFor="field-placeholder">Placeholder</Label>
          <Input
            id="field-placeholder"
            value={selectedField.placeholder || ''}
            onChange={(e) => updateField({ placeholder: e.target.value })}
            className="mt-1"
            readOnly={readOnly}
            disabled={readOnly}
          />
        </div>

        <div className="flex items-center space-x-2">
          <Checkbox
            id="field-required"
            checked={selectedField.required}
            onCheckedChange={(checked) => updateField({ required: !!checked })}
            disabled={readOnly}
          />
          <Label htmlFor="field-required">Required field</Label>
        </div>

        {(selectedField.type === 'select' || selectedField.type === 'radio' || selectedField.type === 'checkbox') && (
          <div>
            <Label>Options</Label>
            <div className="space-y-2 mt-2">
              {selectedField.options?.map((option, index) => (
                <div key={index} className="flex gap-2">
                  <Input
                    value={option}
                    onChange={(e) => updateOption(index, e.target.value)}
                    placeholder={`Option ${index + 1}`}
                    readOnly={readOnly}
                    disabled={readOnly}
                  />
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => removeOption(index)}
                    disabled={readOnly}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              ))}
              {!readOnly && (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={addOption}
                  className="w-full"
                >
                  <Plus className="h-4 w-4 mr-2" />
                  Add Option
                </Button>
              )}
            </div>
          </div>
        )}

        {/* Scoring Configuration */}
        <div className="border-t pt-4">
          <div className="flex items-center space-x-2 mb-4">
            <Checkbox
              id="enable-scoring"
              checked={selectedField.scoring?.enabled || false}
              onCheckedChange={(checked) => updateScoring({ enabled: !!checked })}
              disabled={readOnly}
            />
            <Label htmlFor="enable-scoring">Enable scoring for this field</Label>
          </div>

          {selectedField.scoring?.enabled && (
            <div className="space-y-4">
              <div>
                <Label htmlFor="max-points">Maximum Points</Label>
                <Input
                  id="max-points"
                  type="number"
                  value={selectedField.scoring.maxPoints || 10}
                  onChange={(e) => updateScoring({ maxPoints: parseInt(e.target.value) || 10 })}
                  className="mt-1"
                  readOnly={readOnly}
                  disabled={readOnly}
                />
              </div>

              <div>
                <Label htmlFor="weight-multiplier">Weight Multiplier</Label>
                <Select
                  value={selectedField.scoring.weightMultiplier?.toString() || "1"}
                  onValueChange={(value) => updateScoring({ weightMultiplier: parseInt(value) })}
                  disabled={readOnly}
                >
                  <SelectTrigger className="mt-1">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">1x (Normal)</SelectItem>
                    <SelectItem value="2">2x (Double)</SelectItem>
                    <SelectItem value="3">3x (Triple)</SelectItem>
                    <SelectItem value="4">4x (Quadruple)</SelectItem>
                    <SelectItem value="5">5x (Quintuple)</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {(selectedField.type === 'select' || selectedField.type === 'radio' || selectedField.type === 'checkbox') && (
                <div>
                  <Label>Correct Answers</Label>
                  <div className="space-y-2 mt-2">
                    {selectedField.scoring.correctAnswers?.map((answer, index) => (
                      <div key={index} className="flex gap-2">
                        <Select
                          value={answer}
                          onValueChange={(value) => updateCorrectAnswer(index, value)}
                          disabled={readOnly}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select correct answer" />
                          </SelectTrigger>
                          <SelectContent>
                            {selectedField.options?.map((option, optIndex) => (
                              <SelectItem key={optIndex} value={option}>
                                {option}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => removeCorrectAnswer(index)}
                          disabled={readOnly}
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    ))}
                    {!readOnly && (
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={addCorrectAnswer}
                        className="w-full"
                      >
                        <Plus className="h-4 w-4 mr-2" />
                        Add Correct Answer
                      </Button>
                    )}
                  </div>
                </div>
              )}

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="manual-review"
                  checked={selectedField.scoring.requiresManualReview || false}
                  onCheckedChange={(checked) => updateScoring({ requiresManualReview: !!checked })}
                  disabled={readOnly}
                />
                <Label htmlFor="manual-review">Requires manual review</Label>
              </div>
            </div>
          )}
        </div>

        <div>
          <Label htmlFor="validation-message">Validation Message</Label>
          <Textarea
            id="validation-message"
            value={selectedField.validation?.message || ''}
            onChange={(e) => updateField({ 
              validation: { 
                ...selectedField.validation, 
                message: e.target.value 
              } 
            })}
            placeholder="Custom validation message"
            className="mt-1"
            rows={2}
            readOnly={readOnly}
            disabled={readOnly}
          />
        </div>
      </CardContent>
    </Card>
  );
};
