// Angular/src/app/features/forms/field-palette/field-palette.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormField } from '../../../models/form.model';

@Component({
  selector: 'app-field-palette',
  templateUrl: './field-palette.component.html',
  styleUrls: ['./field-palette.component.scss']
})
export class FieldPaletteComponent {
  @Output() addField = new EventEmitter<FormField>();
  
  fieldTypes = [
    { type: 'text', label: 'Text Input', icon: 'text_fields' },
    { type: 'email', label: 'Email', icon: 'email' },
    { type: 'number', label: 'Number', icon: 'tag' },
    { type: 'textarea', label: 'Textarea', icon: 'notes' },
    { type: 'select', label: 'Dropdown', icon: 'arrow_drop_down_circle' },
    { type: 'radio', label: 'Radio Button', icon: 'radio_button_checked' },
    { type: 'checkbox', label: 'Checkbox', icon: 'check_box' },
    { type: 'date', label: 'Date Picker', icon: 'calendar_today' },
    { type: 'file', label: 'File Upload', icon: 'upload_file' },
    { type: 'rating', label: 'Rating', icon: 'star' },
    { type: 'signature', label: 'Signature', icon: 'draw' }
  ];
  
  handleAddField(type: string): void {
    const newField: Partial<FormField> = {
      type,
      label: `New ${type} field`,
      required: false
    };
    
    // Add options for fields that need them
    if (['select', 'radio', 'checkbox'].includes(type)) {
      newField.options = ['Option 1', 'Option 2'];
    }
    
    this.addField.emit(newField as FormField);
  }
  
  onDragStart(event: DragEvent, type: string): void {
    if (event.dataTransfer) {
      event.dataTransfer.setData('application/json', JSON.stringify({
        source: 'palette',
        fieldType: type
      }));
      event.dataTransfer.effectAllowed = 'copy';
    }
  }
}
<mat-card class="field-palette-card">
  <mat-card-header>
    <mat-card-title>Form Fields</mat-card-title>
    <mat-card-subtitle>Drag fields to the canvas to add them</mat-card-subtitle>
  </mat-card-header>
  
  <mat-card-content class="field-palette-content">
    <button mat-stroked-button 
            *ngFor="let field of fieldTypes"
            class="field-button"
            (click)="handleAddField(field.type)"
            draggable="true"
            (dragstart)="onDragStart($event, field.type)">
      <mat-icon>{{ field.icon }}</mat-icon>
      <span>{{ field.label }}</span>
    </button>
  </mat-card-content>
</mat-card>

// src/components/FieldPalette.tsx

import { FormField } from "@/types/form";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { 
  Type, 
  Mail, 
  Hash, 
  MessageSquare, 
  ChevronDown, 
  CheckCircle, 
  Calendar, 
  Upload, 
  Star,
  PenTool
} from "lucide-react";

interface FieldPaletteProps {
  onAddField: (field: FormField) => void;
}

const fieldTypes = [
  { type: 'text' as const, label: 'Text Input', icon: Type },
  { type: 'email' as const, label: 'Email', icon: Mail },
  { type: 'number' as const, label: 'Number', icon: Hash },
  { type: 'textarea' as const, label: 'Textarea', icon: MessageSquare },
  { type: 'select' as const, label: 'Dropdown', icon: ChevronDown },
  { type: 'radio' as const, label: 'Radio Button', icon: CheckCircle },
  { type: 'checkbox' as const, label: 'Checkbox', icon: CheckCircle },
  { type: 'date' as const, label: 'Date Picker', icon: Calendar },
  { type: 'file' as const, label: 'File Upload', icon: Upload },
  { type: 'rating' as const, label: 'Rating', icon: Star },
  { type: 'signature' as const, label: 'Signature', icon: PenTool },
];

export const FieldPalette = ({ onAddField }: FieldPaletteProps) => {
  const handleAddField = (type: FormField['type']) => {
    const newField: Omit<FormField, 'id'> = {
      type,
      label: `New ${type} field`,
      required: false,
      ...(type === 'select' || type === 'radio' || type === 'checkbox' ? { options: ['Option 1', 'Option 2'] } : {}),
    };
    
    onAddField(newField as FormField);
  };

  const handleDragStart = (e: React.DragEvent, type: FormField['type']) => {
    e.dataTransfer.setData('application/json', JSON.stringify({
      source: 'palette',
      fieldType: type
    }));
    e.dataTransfer.effectAllowed = 'copy';
  };

  return (
    <Card className="h-full">
      <CardHeader>
        <CardTitle className="text-lg">Form Fields</CardTitle>
        <p className="text-sm text-gray-500">Drag fields to the canvas to add them</p>
      </CardHeader>
      <CardContent className="space-y-2">
        {fieldTypes.map(({ type, label, icon: Icon }) => (
          <Button
            key={type}
            variant="outline"
            className="w-full justify-start gap-3 h-12 cursor-grab active:cursor-grabbing"
            draggable
            onDragStart={(e) => handleDragStart(e, type)}
            onClick={() => handleAddField(type)}
          >
            <Icon className="h-4 w-4" />
            {label}
          </Button>
        ))}
      </CardContent>
    </Card>
  );
};
